export const TIME_ITEMS = [
  { key: "AM_06", label: "오전 6시", type: "AM" },
  { key: "AM_07", label: "오전 7시", type: "AM" },
  { key: "AM_08", label: "오전 8시", type: "AM" },
  { key: "AM_09", label: "오전 9시", type: "AM" },
  { key: "AM_10", label: "오전 10시", type: "AM" },
  { key: "AM_11", label: "오전 11시", type: "AM" },
  { key: "PM_12", label: "정오 12시", type: "PM" },
  { key: "PM_01", label: "오후 1시", type: "PM" },
  { key: "PM_02", label: "오후 2시", type: "PM" },
  { key: "PM_03", label: "오후 3시", type: "PM" },
  { key: "PM_04", label: "오후 4시", type: "PM" },
  { key: "PM_05", label: "오후 5시", type: "PM" },
  { key: "PM_06", label: "오후 6시", type: "PM" },
  { key: "PM_07", label: "오후 7시", type: "PM" },
  { key: "PM_08", label: "오후 8시", type: "PM" },
  { key: "PM_09", label: "오후 9시", type: "PM" },
  { key: "PM_10", label: "오후 10시", type: "PM" },
] 
